# [[plugins]]
# repo = 'rhysd/vim-operator-surround'
# depends = 'vim-operator-user'
# on_map = { n = '<Plug>' }
# hook_add = '''
# " add ```...``` surround when filetype is markdown
# let g:operator#surround#blocks = {
#     \ 'markdown' : [
#     \   { 'block' : ["```\n", "\n```"], 'motionwise' : ['line'], 'keys' : ['`'] },
#     \ ] }

# " operator mappings
# map <silent>sa <Plug>(operator-surround-append)
# map <silent>sd <Plug>(operator-surround-delete)
# map <silent>sr <Plug>(operator-surround-replace)
# '''

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'