theme = "catppuccin_macchiato"

[editor]
idle-timeout = 20
cursorline = true
color-modes = true
bufferline = "always"
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
# newline = "⏎"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
C-t = ":sh tmux popup -d \"#{pane_current_path}\" "


[keys.normal."["]
b = ":bnext"
[keys.normal."]"]
b = ":bprev"

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
