[helpers]
color_rgb = ".dotter/helpers/color_rgb.rhai"

[shell.files]
# Optional local variables: email+git_username
# git = "~/.gitconfig"
ripgrep = { type = "symbolic", target = "~/.ripgreprc", if = '(is_executable "rg")'}
bat = "~/.config/bat"

[zsh]
depends = ["shell"]

[zsh.files]
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"
p10k = "~/.p10k.zsh"

[helix.files]
helix = { type = "symbolic", target = "~/.config/helix" }

[kitty.files]
kitty = { type = "symbolic", target = "~/.config/kitty" }

[vim.files]
vimrc = { type = "symbolic", target = "~/.vimrc" }
